import 'src/styles/globals.css';
import { pretendard } from 'src/theme/fonts';
import type { AppProps } from 'next/app';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <style jsx global>{`
        html,
        body {
          font-family: ${pretendard.style.fontFamily};
        }
      `}</style>

      <Head>
        <title>today&apos;s words</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Component {...pageProps} />
    </>
  );
}
